project:
  type: website

website:
  title: "Sam Watts"
  favicon: favicon.ico
  open-graph: true
  navbar:
    background: "#000000"
    right:
      - about.qmd
      - index.qmd
      - notes.qmd
      - aoc/aoc.qmd
      - icon: github
        href: https://github.com/sam-watts

  comments:
    utterances:
      repo: sam-watts/blog
  
format:
  html:
    theme: flatly
    css: styles.css

execute:
  freeze: true

toc: true
toc-location: left
cap-location: margin

