project:
  type: website

website:
  title: "Sam Watts - Blog"
  favicon: favicon.ico
  open-graph: true
  navbar:
    background: "#008E97"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sam-watts

  comments:
    utterances:
      repo: sam-watts/blog

theme:
  light: flatly
  dark: darkly
  
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto